---
- name: Create new {{ application_name }} project
  command: oc new-project {{ application_name }}

- name: Copy openshift template
  template:
    src: hello-pod.j2
    dst: "{{ template_path }}"

- name: Create new {{ application_name }} app
  command: oc create -f {{ template_path }} --name {{ application_name }}
